name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure system
      run: sudo apt install bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils

    - name: Configure Linux
      run: make defconfig && ./scripts/config --file .config --set-str LOCALVERSION "-squatchos"

    - name: Build!!
      run: make -j$(nproc) 2>&1 | tee log

    - name: GitHub Push
      # You may pin to the exact commit or the version.
      # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: $\{{ secrets.GITHUB_TOKEN }}
          
      
