name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure system
      run: sudo apt install bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils

    - name: Configure Linux
      run: make defconfig && ./scripts/config --file .config --set-str LOCALVERSION "-squatchos"

    - name: Build!!
      run: make -j$(nproc) 2>&1 | tee log
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.1.0
      with:
    # Artifact name
        name: kernel
    # A file, directory or wildcard pattern that describes what to upload
        path: ./*
    # The desired behavior if no files are found using the provided path.
